/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#3e2c2b",
        "tertiary": "#00694e",
        "on-primary-container": "#fffbff",
        "surface-dim": "#f1d3d2",
        "on-secondary-container": "#5e6473",
        "on-surface": "#271717",
        "on-tertiary-fixed": "#002116",
        "secondary": "#1a202c",
        "tertiary-fixed-dim": "#60dcb0",
        "primary": "#ff4655",
        "surface-container-high": "#ffe1e0",
        "tertiary-container": "#008564",
        "surface-container-low": "#fff0ef",
        "secondary-container": "#dde2f3",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#ffb3b2",
        "on-primary-fixed-variant": "#92001f",
        "on-primary-fixed": "#410008",
        "surface-variant": "#fadbda",
        "on-secondary-fixed-variant": "#414754",
        "on-surface-variant": "#5b403f",
        "surface": "#fff8f7",
        "on-tertiary-container": "#f5fff8",
        "primary-container": "#dd2c40",
        "on-tertiary-fixed-variant": "#00513c",
        "inverse-on-surface": "#ffedec",
        "surface-container-highest": "#fadbda",
        "surface-container": "#ffe9e8",
        "primary-fixed": "#ffdad9",
        "secondary-fixed-dim": "#c1c6d7",
        "error-container": "#ffdad6",
        "surface-bright": "#fff8f7",
        "secondary-fixed": "#dde2f3",
        "on-secondary-fixed": "#161c27",
        "tertiary-fixed": "#7ff9cc",
        "on-error": "#ffffff",
        "surface-tint": "#bd0c2d",
        "primary-fixed-dim": "#ffb3b2",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#271717",
        "outline": "#906f6e",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "background": "#f3f4f6",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#e4bdbc"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "stack-gap-md": "24px",
        "container-max-width": "600px",
        "stack-gap-lg": "32px",
        "stack-gap-sm": "16px",
        "inner-padding-mobile": "24px",
        "inner-padding": "40px"
      },
      fontFamily: {
        "display-hero": ["Montserrat"],
        "headline-lg-mobile": ["Montserrat"],
        "label-sm": ["Inter"],
        "headline-md": ["Montserrat"],
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Montserrat"]
      },
      fontSize: {
        "display-hero": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "30px", "fontWeight": "700"}],
        "label-sm": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "headline-md": ["20px", {"lineHeight": "26px", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["28px", {"lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
